name = "atomvm_packgleam"
version = "0.8.1"
target = "erlang"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Pack an AtomVM .avm file from your gleam project"
licences = ["Apache-2.0"]
repository = { type = "github", user = "karlsson", repo = "atomvm_packgleam" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
tom = ">= 1.1.1 and < 2.0.0"
atomvm_packbeam = ">= 0.7.2"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
